# Generated by Django 4.0.3 on 2022-04-26 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aman',
            name='id',
        ),
        migrations.AlterField(
            model_name='aman',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=254, primary_key=True, serialize=False),
        ),
    ]
