# Generated by Django 4.0.3 on 2022-04-26 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_aman_id_alter_aman_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aman1',
            name='email',
            field=models.EmailField(default=None, max_length=890),
        ),
    ]
