# Generated by Django 4.0.3 on 2022-04-26 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_aman1_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aman',
            name='email',
            field=models.EmailField(blank=True, default=False, max_length=890, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='aman1',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=890, null=True),
        ),
    ]
