# Generated by Django 4.0.3 on 2022-04-26 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_aman_email_alter_aman1_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aman1',
            name='name',
        ),
        migrations.RemoveField(
            model_name='aman1',
            name='roll_no',
        ),
    ]
