# Generated by Django 4.0.3 on 2022-04-26 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_aman1_name_remove_aman1_roll_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aman',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=890, primary_key=True, serialize=False),
        ),
    ]
